import type { LucideIcon } from "lucide-react";
import {
	BadgeDollarSign,
	BookMarked,
	Bookmark,
	BookOpen,
	Bot,
	Briefcase,
	Calendar,
	Camera,
	ClipboardList,
	Code2,
	Coffee,
	Dribbble,
	Facebook,
	Figma,
	FileSpreadsheet,
	FileText,
	Gamepad2,
	Gift,
	Github,
	Globe,
	GraduationCap,
	Heart,
	House,
	Image,
	Instagram,
	Laptop,
	Link2,
	Linkedin,
	Mail,
	Map as MapIcon,
	MapPin,
	Megaphone,
	MessageCircle,
	Mic,
	MonitorPlay,
	Music,
	Newspaper,
	Package,
	PenTool,
	Phone,
	Podcast,
	Presentation,
	Rss,
	Send,
	ShieldCheck,
	ShoppingBag,
	ShoppingCart,
	Slack,
	Smartphone,
	Sparkles,
	Star,
	Terminal,
	Ticket,
	Trophy,
	Twitch,
	Users,
	Video,
	Wallet,
	Wrench,
	X,
	Youtube,
} from "lucide-react";

import type { LinkIconKey } from "#/lib/link-icon-keys";

export interface LinkIconOption {
	key: LinkIconKey;
	label: string;
	Icon: LucideIcon;
}

export const LINK_ICON_OPTIONS: LinkIconOption[] = [
	{ key: "globe", label: "Website", Icon: Globe },
	{ key: "link-2", label: "Link", Icon: Link2 },
	{ key: "house", label: "Home", Icon: House },
	{ key: "mail", label: "Email", Icon: Mail },
	{ key: "phone", label: "Phone", Icon: Phone },
	{ key: "message-circle", label: "Chat", Icon: MessageCircle },
	{ key: "briefcase", label: "Services", Icon: Briefcase },
	{ key: "graduation-cap", label: "Teaching", Icon: GraduationCap },
	{ key: "laptop", label: "Portfolio", Icon: Laptop },
	{ key: "file-spreadsheet", label: "Spreadsheet", Icon: FileSpreadsheet },
	{ key: "image", label: "Gallery", Icon: Image },
	{ key: "mic", label: "Audio", Icon: Mic },
	{ key: "pen-tool", label: "Design", Icon: PenTool },
	{ key: "presentation", label: "Slides", Icon: Presentation },
	{ key: "shopping-cart", label: "Store", Icon: ShoppingCart },
	{ key: "shield-check", label: "Trust", Icon: ShieldCheck },
	{ key: "star", label: "Favorites", Icon: Star },
	{ key: "trophy", label: "Achievements", Icon: Trophy },
	{ key: "users", label: "Community", Icon: Users },
	{ key: "wrench", label: "Tools", Icon: Wrench },
	{ key: "coffee", label: "Support", Icon: Coffee },
	{ key: "heart", label: "Support me", Icon: Heart },
	{ key: "package", label: "Products", Icon: Package },
	{ key: "bookmark", label: "Bookmarks", Icon: Bookmark },
	{ key: "smartphone", label: "App", Icon: Smartphone },
	{ key: "send", label: "Contact", Icon: Send },
	{ key: "bot", label: "AI", Icon: Bot },
	{ key: "megaphone", label: "Announcements", Icon: Megaphone },
	{ key: "wallet", label: "Payments", Icon: Wallet },
	{ key: "gift", label: "Giveaway", Icon: Gift },
	{ key: "clipboard-list", label: "Checklist", Icon: ClipboardList },
	{ key: "monitor-play", label: "Live", Icon: MonitorPlay },
	{ key: "code-2", label: "Code", Icon: Code2 },
	{ key: "sparkles", label: "Highlights", Icon: Sparkles },
	{ key: "book-marked", label: "Reading", Icon: BookMarked },
	{ key: "map", label: "Directions", Icon: MapIcon },
	{ key: "terminal", label: "Devlog", Icon: Terminal },
	{ key: "calendar", label: "Schedule", Icon: Calendar },
	{ key: "shopping-bag", label: "Shop", Icon: ShoppingBag },
	{ key: "badge-dollar-sign", label: "Donate", Icon: BadgeDollarSign },
	{ key: "ticket", label: "Tickets", Icon: Ticket },
	{ key: "podcast", label: "Podcast", Icon: Podcast },
	{ key: "music", label: "Music", Icon: Music },
	{ key: "video", label: "Video", Icon: Video },
	{ key: "camera", label: "Photos", Icon: Camera },
	{ key: "newspaper", label: "News", Icon: Newspaper },
	{ key: "file-text", label: "Articles", Icon: FileText },
	{ key: "map-pin", label: "Location", Icon: MapPin },
	{ key: "gamepad-2", label: "Gaming", Icon: Gamepad2 },
	{ key: "book-open", label: "Courses", Icon: BookOpen },
	{ key: "rss", label: "Updates", Icon: Rss },
	{ key: "instagram", label: "Instagram", Icon: Instagram },
	{ key: "youtube", label: "YouTube", Icon: Youtube },
	{ key: "x", label: "X", Icon: X },
	{ key: "facebook", label: "Facebook", Icon: Facebook },
	{ key: "linkedin", label: "LinkedIn", Icon: Linkedin },
	{ key: "github", label: "GitHub", Icon: Github },
	{ key: "twitch", label: "Twitch", Icon: Twitch },
	{ key: "slack", label: "Slack", Icon: Slack },
	{ key: "figma", label: "Figma", Icon: Figma },
	{ key: "dribbble", label: "Dribbble", Icon: Dribbble },
];

export const LINK_ICON_OPTIONS_BY_KEY: Record<LinkIconKey, LinkIconOption> =
	Object.fromEntries(
		LINK_ICON_OPTIONS.map((option) => [option.key, option]),
	) as Record<LinkIconKey, LinkIconOption>;
